spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inixindobdg
    username: inixindobdg
    password: inixindobdg
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
